### ISSUE TITLE
FBP project manifest (fbp.json)

### ISSUE THREAD

**Issue by paulyoung** [noflo/noflo#247]
Rather than adding components to `package.json` that aren't part of the spec, these could exist in a `noflo.json` file.

Decoupling NoFlo from npm would allow the use of other package managers such as Bower.

**Comment by bergie** [comment]
I finally started setting this up. First part is agreeing on the schema format. Initial proposal at https://github.com/flowbased/fbp-manifest/tree/master/schemata
(JSON schema formatted as YAML for more human-friendly editing)

**Comment by bergie** [comment]
Here's an example of a `fbp.json` file generated with the tool: https://gist.github.com/bergie/159b7df7139af48018ea

This one is interesting since the noflo-image module has three types of NoFlo components:

* Components that work in both browser and Node.js (runtime `noflo`)
* Components that work only in Node.js (runtime `noflo-nodejs`)
* Components that work only in Node.js (runtime `noflo-browser`)

**Comment by bergie** [comment]
Closing this ticket in favor of continuing the discussion over at https://github.com/flowbased/fbp-manifest
