### ISSUE TITLE
Process API: Brackets not being forwarded for errors

### ISSUE THREAD

**Issue by bergie** [noflo/noflo#444]
When using `output.sendDone(new Error())`, Process API doesn't forward brackets.

Here's an example:
https://travis-ci.org/noflo/noflo-rss/builds/134564008#L266

cc/ @trustmaster

**Comment by trustmaster** [comment]
Here is what's happening there:

1. An opening bracket arrives and is buffered
2. Data arrives and triggers the async process function
3. A closing bracket arrives and triggers `dropEmptyBrackets` handling code
4. `dropEmptyBrackets` looks at the buffer but doesn't see the data between open and close bracket in the buffer, so it decides to drop them
5. Process function sends the error but it's too late to wrap it with brackets

The desired behavior for it is to add a pending data item to the output queue on step 2, so that it doesn't drop the brackets on step 4. Adding that requires also dropping the pending data item together with brackets if the process function never sends data between those brackets.

**Comment by bergie** [comment]
Fixed via #449
