### ISSUE TITLE
Process API bracket forwarding needs to be scoped to the packets actually used

### ISSUE THREAD

**Issue by bergie** [noflo/noflo#465]
The bracket forwarding done by Process API should be based on the IPs read from the buffer, not the overall state of the buffer.

A component that fires when two inports have data may have problems otherwise. If we have `bracketForwarding` set to `in1` in component that waits until both ports have data that receives the following IPs:

```
IN1: < 2
IN1: DATA
IN1 >
IN2 <1
IN2 DATA
IN2 >
```

The component will actually get the `in1` packet from buffer only when we've received data from `in2`. This causes the following output stream:

```
< 2
>
DATA
```

Instead of the expected:

```
< 2
DATA
>
```
#463 provides a red test for this.

**Comment by trustmaster** [comment]
The only way to implement this that i can think of is doing it the same way WirePattern did: maintain separate buffers for forwarded brackets (separate buffer per port/scope) and flush them at once when there is data to flush them with.

**Comment by bergie** [comment]
Some snippets from a discussion with @trustmaster yesterday:

Bergie:
> so basically:
`input.get` -> prepare preceding brackets for forwarding
`output.send` -> forward brackets first, then send data. Keep track of which port(s) we sent to. Each should get brackets forwarded
`output.done` -> forward all closing brackets that came after the data to all ports we forwarded brackets (and sent output) to

> so if the stream was
`<1 <2 A 2> B 1>`
we'd send on first firing:
`<1 <2 A`
then on first done:
`2>`
then second firing:
`B`
second done:
`1>`

Trustmaster:

> right, nice, but doesn’t cover the case when the input stream is closed after the 2nd done

Bergie:

> true. But if there is no in-flight process, we can probably just forward closeBrackets as-is

Trustmaster:

> ok, next: what if there are `get()` and `done()` but not `send()` to a forwarded port? drop all the brackets or wait until next activation which may utilize them?

Bergie:

> [drop, and] so in the example, if `A` didn't send, we'd have to keep `<1` in stock for next firing

> but not `<2 2>` since they were only related to `A`

**Comment by trustmaster** [comment]
To give you guys some idea of the stuff i'm facing with this humble tiny issue and why it's taking so long. Got an interesting case while debugging today.

In this component: https://github.com/noflo/noflo/blob/master/spec/Component.coffee#L1101

A simplified description of what's happening there. Here's the stream on the input:

```
<msg>
<delay>
one, delay: 30
two, delay: 0
three, delay: 20
four, delay: 10
five, delay: -40
</delay>
</msg>
```

So, because of the delays, the results are yielded to `out` in sequence: `two, four, three, one`. And `five` fails immediately and sends to `error`. But the input/output is ordered, so it will still send it to output in sequence it arrived on input: `one, two, three, four, five`.

As the error happens first, it forwards brackets to `error` port, so `five` gets wrapped with `<msg><delay> five </delay></msg>`. Which is expected (?). But as this way brackets have successfully been forwarded, the results sent to `out` port later on don't get wrapped with brackets. Which is unexpected (?).

I foresee comments like "OK, just make it forward the brackets to the main port as well, because we kind of expect it". Easy to say, because currently the framework maintains just 1 buffer for brackets, and sends them to the port that actually gets sent to, without being aware of what else may come in future.

I have an idea how to "fix" this: maintain separate bracket buffer per output. Which complicates things. Another idea is to make the framework scan the output queue back and forth to decide where to send brackets, but it complicates things even more, probably a lot more.

**Comment by trustmaster** [comment]
Here is the current state of bracket forwarding. We now have 2 different implementations of bracket forwarding:

1. In `master` branch, based on inserting brackets into certain points of the output queue
  - Pros: works well with async components with 1 in port or multiple ports joined by simple logical AND
  - Cons: doesn't work with async components which don't send output on every successful precondition, e.g. fails with the test in the top post of this thread
2. In `bracket_forwarding` branch, based on dedicated bracket buffers which are flushed on `output.send()` and `output.done()`
  - Pros: works with async components which don't send output on every successful precondition, i.e. passes the test in the top post of this thread
  - Cons: produces wrong results if the input stream is processed concurrently with `output.send()` and `output.done()` being called in an order different from the expected output, e.g. fails the test described in previous post

That means yet another model is needed to solve the bracket forwarding problem. Maybe something like hybrid: output + bracket queues with bracket queues sliding along the output queue as needed. I'm not sure if generic automatic bracket forwarding is at all possible with async functions and multiple inputs/outputs.

**Comment by trustmaster** [comment]
Note: above comment updated.

**Comment by bergie** [comment]
Now another stab at this in #518, able to pass the curveballs from #463
