### ISSUE TITLE
WirePattern does not respect required: false

### ISSUE THREAD

**Issue by JamesHagerman** [noflo/noflo#490]
Hi there,

I've got a component that has two inports, one of which I want to be required, one of which is optional.

The current config looks something like this:

``` javascript
c.inPorts = new noflo.InPorts({
    url: {
        datatype: 'string',
        required: false
    },
    field: {
        datatype: 'string',
        required: true
    }
});
```

The issue is that the components WirePattern does not run at all unless I either add a `default` data block to the url inport's config, or if I actually send data into the url port.

Based on the components documentation (noflojs.org/documentation/components/) I would expect `required: false` to allow the wirepattern to run without data from the inport marked as such.

This seems like a bug but I can't tell. I know there is the upcoming `Process` method of building components but we are not ready to switch to that right now.

Thanks for the help,
James

**Comment by JamesHagerman** [comment]
Oh, also, this seems at odds with what was done in response to #238...

**Comment by aretecode** [comment]
@JamesHagerman 

It sounds as though what you are using is a `param` port. 

```coffeescript
exports.getComponent = ->
  c = new noflo.Component
    inPorts:
      url: 
        datatype: 'string'
        required: false
      field: 
        datatype: 'string'
        required: true

  noflo.helpers.WirePattern c,
    in: ['field']
    params: ['url']
  , (field, groups, out, done) ->
    console.log field 
    console.log c.params.url
    done()
```

The documentation is being updated here https://aretecode.github.io/noflo.github.io/documentation/legacy/

**Comment by JamesHagerman** [comment]
Oh wow!!!! Thank you for the quick and detailed response!!!

That's way more information than I was expecting and it answers a heck of a lot of other questions to boot! Thank you!

Looking through it in detail now!

**Comment by aretecode** [comment]
@JamesHagerman

Happy to help! Feel free to ask if you have any more questions.

The updated docs will go live when they are finished being reviewed by the rest of the noflo team (some have already reviewed it), hopefully that is soon. If you spot any typos or anything that is not clear, let me know.

**Comment by JamesHagerman** [comment]
@aretecode Cool! I know the rest of my team looks forward to updated docs!

One thing that has remained a little confusing to the lot of us over here are exactly how Groups work. It might be nice to make that a tad more clear in the updated docs.

**Comment by aretecode** [comment]
@JamesHagerman

**Comment by JamesHagerman** [comment]
@aretecode I just tried your example, and for some reason, using `params` with required set to false is also exhibiting the same issue.

Unless I set the `url` inport to `required: true` and either set `default` data on it or wire up a connection to that inport, c.params.url is undefined when the WirePattern actually runs.

Also, that `done` call back is also undefined.

Annnnnd I _just_ realized that there is a newer release than what we're using. We're on noflo@0.7.4.

Let me update to 0.7.8 and see if that fixes things.

**Comment by aretecode** [comment]
@JamesHagerman 

Are you sending `url` _after_ sending `field` ?

When all of the ports defined in the `in` param and the required `param` ports have `data`, WirePattern callback is triggered.

So if you send `url` before `field`, it will be there. If you send `url` after `field`, it is triggered before `url` arrives.

Sorry in my example, `done` is the callback for `async: true` on WirePattern, if it is not `async`, you do not need it. Most of my components are `async` and Process API is naturally `async` so I'm used to putting it in there.

Using the `async: true` would look like this:
```
exports.getComponent = ->
  c = new noflo.Component
    inPorts:
      url: 
        datatype: 'string'
        required: false
      field: 
        datatype: 'string'
        required: true

  noflo.helpers.WirePattern c,
    in: ['field']
    params: ['url']
    async: true
  , (field, groups, out, done) ->
    console.log field 
    console.log c.params.url
    done()
```

**Comment by aretecode** [comment]
@JamesHagerman 
I will see about doing that with groups, thank you! 

## Docs

Groups are pretty much just things that you can use to group things. They are replaced by Brackets in the latest noflo
https://aretecode.github.io/noflo.github.io/documentation/process-api/#brackets

## Resources 

A fairly simple usage can be found here:
https://github.com/aretecode/noflo-objects/blob/master/components/SplitObject.coffee

And here for the documentation example project:
https://github.com/aretecode/canadianness/blob/master/components/FindWords.coffee#L60
(which is detailed more here https://aretecode.github.io/noflo.github.io/projects/)


## Example 

(there are many other uses for groups, such as database query results)
Say you have a bunch of individual data and you want to send groups of it:

```coffeescript
fruits =  ['apples', 'bananas', 'grapes', 'oranges']
veggies = ['broccoli', 'cabbage', 'celery']

# or for Process API, output.ports.name.send new noflo.IP 'openBracket', 'fruit'
output.ports.name.openGroup 'fruit'
for fruit in fruits
  output.ports.name.send fruit
# or for Process API, output.ports.name.send new noflo.IP 'closeBracket', 'fruit'
output.ports.name.closeGroup 'fruit'

# or for Process API, output.ports.name.send new noflo.IP 'openBracket', 'veggies'
output.ports.name.openGroup 'veggies'
for veggie in veggies
  output.ports.name.send veggie
# or for Process API, output.ports.name.send new noflo.IP 'closeBracket', 'veggies'
output.ports.name.closeGroup 'veggies'
```

## Avoid 

With all that being said, I personally avoid using them (and some repositories we have do not use them at all) because they can become overly complex (especially when dealing with forwarding), and you can easily just send an object instead:

```coffeescript
output.ports.name.send 
  name: 'fruit'
  data: fruits

output.ports.name.send 
  name: 'veggies'
  data: veggies
```

**Comment by JamesHagerman** [comment]
@aretecode Alright, that was the issue after all. Order matters!

Thank you for the help and for the notes on how Groups work!

One more note on the docs: The `WirePattern Async` link above the Wirepattern header on that legacy page is a broken link...

**Comment by aretecode** [comment]
@JamesHagerman 

## Order & Params
Another thing that matters is a `param` ports data will stay until it is replaced.
So if you:

- 1) send `example.com` to `url`
- 2) send `eh` to `field` 

(it will trigger and have `example.com` as `c.params.url` and `eh` as `field`)

- 3) send `canada` to `field`

(it will trigger and have `example.com` as `c.params.url` and `canada` as `field`)

- 4) send `igloo.com` to `url`
- 5) send `moose` to `field`

(it will trigger and have `igloo.com` as `c.params.url` and `moose` as `field`)

## Link
The reason that link is broken is because it goes to the base url, which is made for http://noflojs.org/documentation/tooling/

So for example 
https://aretecode.github.io/documentation/legacy/#async 

actually needs `/noflo.github.io/` as in 
https://aretecode.github.io/noflo.github.io/documentation/legacy/#async

However, this wont be changed because then all of the links would need to be changed for this domain, and then changed again for the live official version.

## Groups
I've updated the docs with that stuff about groups/brackets:
https://github.com/aretecode/noflo.github.io/commit/15711868abc7015e136e73e2bd5dae6135cf95dc

**Comment by JamesHagerman** [comment]
Yeah, the ordering in NoFlo has caught us off guard a few times.
And that makes sense for the link as well! Thanks, yet again!

Feel free to close this if you'd like. Not sure if discussions are to be closed or not...
